//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matrimonial_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat
    {
        public int c_id { get; set; }
        public string c_user_1 { get; set; }
        public string c_user_2 { get; set; }
        public Nullable<int> chat_status { get; set; }
    
        public virtual user_profile user_profile { get; set; }
        public virtual user_profile user_profile1 { get; set; }
    }
}
