//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matrimonial_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class successful_stories
    {
        public int s_id { get; set; }
        public string u_id { get; set; }
        public string rating { get; set; }
        public Nullable<int> story_status { get; set; }
        public string title { get; set; }
        public string description_ { get; set; }
    
        public virtual user_profile user_profile { get; set; }
    }
}
