//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matrimonial_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_profile()
        {
            this.chats = new HashSet<chat>();
            this.chats1 = new HashSet<chat>();
            this.image_gallery = new HashSet<image_gallery>();
            this.successful_stories = new HashSet<successful_stories>();
        }
    
        public string u_id { get; set; }
        public string pass { get; set; }
        public string F_name { get; set; }
        public string L_name { get; set; }
        public string occupation { get; set; }
        public string caste { get; set; }
        public string religion { get; set; }
        public Nullable<int> salary { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chat> chats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chat> chats1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<image_gallery> image_gallery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<successful_stories> successful_stories { get; set; }
    }
}
